### ISSUE TITLE
Source files are not available

### ISSUE THREAD

**Issue by nikiforov-alexander** [strawjs/straw-android#2]
If one clicks on the badge with coverage, coverage report is there, but source files are not available, for example file `StrawPlugin` has following source

/home/travis/build/strawjs/straw-android/src/main/java/org/kt3k/straw/StrawPlugin.java

Which is obviously wrong Path.

Follow the link below to see what I mean:

https://coveralls.io/builds/1892571/source?filename=%2Fhome%2Ftravis%2Fbuild%2Fstrawjs%2Fstraw-android%2Fsrc%2Fmain%2Fjava%2Forg%2Fkt3k%2Fstraw%2FStrawPlugin.java

My question would be : how to modify `build.gradle` or any other file to get it working. 

Major repository *coveralls-gradle-plugin* with plugin itself and not this example works just fine, and the file names there are somewhat like that

 /src/main/groovy/org/kt3k/gradle/plugin/coveralls/CoverallsTask.groovy

I know that this project was not changed for a long time, but any info/help will be appreciated

Thanks :)

**Comment by kt3k** [comment]
Thanks for reporting!

I'll look into it in a few days. (If it doesn't work at all, I'll switch to codecov.io. That's a better alternative of coveralls.)

I didn't abandon this project. Thanks for being interested! 😄

**Comment by kt3k** [comment]
After I set up the root directory path in coveralls.io's page, now it shows the coverage report correctly. (For example, he above link shows the report correctly now.) Thanks.

**Comment by nikiforov-alexander** [comment]
Could you tell how you did it ?

**Comment by nikiforov-alexander** [comment]
Thank you for answer :+1: I finally did that for my repositories as well
